# This file was generated by GoReleaser. DO NOT EDIT.
cask "tile" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "61cea59c22f2e07a5b6e58c0772eac2f6cd19224d6b225f0f69a7378105a44cb"
      url "https://github.com/Slijeff/tile/releases/download/v#{version}/tile_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "aec9f84ae90062db615baa3be6b12567cda6354aacc270246a54d1370fc41009"
      url "https://github.com/Slijeff/tile/releases/download/v#{version}/tile_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "ed2e4c072001ecb4386b5f35ff7f17217997cbc97972a1fd808966b76641410f"
      url "https://github.com/Slijeff/tile/releases/download/v#{version}/tile_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "1f1d4f70adad7974f628f69e6389905a3de0432a386c322029becc9382e3daae"
      url "https://github.com/Slijeff/tile/releases/download/v#{version}/tile_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tile"
  desc "A small tmux-like terminal multiplexer"
  homepage "https://github.com/Slijeff/tile"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tile"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tile"]
    end
  end

  # No zap stanza required
end
