# This file was generated by GoReleaser. DO NOT EDIT.
cask "tile" do
  version "0.1.2"

  on_macos do
    on_arm do
      sha256 "483f904fbc9478facdd798c08d04b5ff639c445ace4c636d68f504651beb328d"
      url "https://github.com/Slijeff/tile/releases/download/v#{version}/tile_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "ded4c5715b2f457954668cf5ed179221b5169add0d32a2afed45098e5b994a44"
      url "https://github.com/Slijeff/tile/releases/download/v#{version}/tile_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "89d154941a5647984d64e887cf15794d5ca0df55b7fb70eacea996ae0d560232"
      url "https://github.com/Slijeff/tile/releases/download/v#{version}/tile_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "0e71fe3561e6f53d0cd7d7d472bf49958711f67b64c15ecec053872470213c7b"
      url "https://github.com/Slijeff/tile/releases/download/v#{version}/tile_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tile"
  desc "A small tmux-like terminal multiplexer"
  homepage "https://github.com/Slijeff/tile"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tile"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tile"]
    end
  end

  # No zap stanza required
end
