# This file was generated by GoReleaser. DO NOT EDIT.
cask "tile" do
  version "0.1.4"

  on_macos do
    on_arm do
      sha256 "ad112b314d9521af7bcba6be8fbdc408d584f366b4d955b1f32a040c4604d29c"
      url "https://github.com/Slijeff/tile/releases/download/v#{version}/tile_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "29fddf0e3e97e3d02b3e60266917f4f470b5655f4efd8dcb4b49233d51bbd0b2"
      url "https://github.com/Slijeff/tile/releases/download/v#{version}/tile_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "40f2f163638fac332e1ae2a84de071af114d5baa79b44d905eeee61a45ae794f"
      url "https://github.com/Slijeff/tile/releases/download/v#{version}/tile_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "a71dc0043571c7e481e8180f04cf34d232094c6055eb74771c6f72bd581da2e4"
      url "https://github.com/Slijeff/tile/releases/download/v#{version}/tile_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tile"
  desc "A small tmux-like terminal multiplexer"
  homepage "https://github.com/Slijeff/tile"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tile"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tile"]
    end
  end

  # No zap stanza required
end
